builtins.concatStringsSep "\n" [
    #####################################################################
    # Completions and styles.

    # Automatic rehash
    "zstyle ':completion:*' rehash true"

    # Initially generated by compinstall, but hand-modified since.
    # Combines ideas from <https://unix.stackexchange.com/a/97349>
    # and <https://stackoverflow.com/a/24237590>.
    "zstyle ':completion:*' completer _complete _ignored _approximate"
    # "zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=* r:|=*'"
    "zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]-_}={[:upper:][:lower:]_-}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'"
]
